version: '3'
services:
#postgres
  postgres:
    image: "postgres:15.5-alpine"
    container_name: postgres_fiap_3soat_g53
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiap
    ports:
      - "5432:5432"
    volumes:
      - ./build/volumes/postgres_data:/var/lib/postgresql/data