version: '3'
services:
#postgres
  postgres:
    image: "postgres:15.5-alpine"
    container_name: postgres_fiap_3soat_g53
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiap
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 172.34.0.2
    volumes:
      - ./build/volumes/postgres_data:/var/lib/postgresql/data
#pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_fiap_3soat_g53
    environment:
      PGADMIN_DEFAULT_EMAIL: "3soatg53@fiap.com"
      PGADMIN_DEFAULT_PASSWORD: "3soatg53"
    ports:
      - "54321:80"
    networks:
      backend:
        ipv4_address: 172.34.0.3
    volumes:
       - ./configs/pgadmin/servers.json:/pgadmin4/servers.json
       - ./configs/pgadmin/pgpass:/pgpass
    depends_on:
      - postgres
#applanchonete
  applanchonete:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: applanchonete
    container_name: applanchonete_fiap_3soat_g53
    environment:
      CONNECTION_STRING: jdbc:postgresql://172.34.0.2:5432/fiap
      DB_PASS: postgres
      DB_USER: postgres
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    networks:
      backend:
        ipv4_address: 172.34.0.4
    depends_on:
      - postgres
#network
networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.34.0.0/24
         gateway: 172.34.0.1
