apiVersion: apps/v1
kind: Deployment
metadata:
  name: applanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applanchonete
  template:
    metadata:
      labels:
        app: applanchonete
    spec:
      containers:
      - name: applanchonete
        image: fvmoraes/applanchonetetok8s
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        envFrom:
          - secretRef:
              name: applanchonete-secret
          - configMapRef:
              name: applanchonete-configmap
