apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- hpa.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: applanchonete
  app.kubernetes.io/managed-by: 3soatg53

secretGenerator:
- name: applanchonete-secret
  type: Opaque
  literals:
  - DB_PASS=postgres
  - DB_USER=postgres

configMapGenerator:
- name: applanchonete-configmap
  literals:
  - CONNECTION_STRING=jdbc:postgresql://rds-db-3soat-g53.c3kwemw84tyy.us-east-1.rds.amazonaws.com:5432/fiap

generatorOptions:
  disableNameSuffixHash: false