apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- persistent-volume-claim.yaml
- persistent-volume.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/managed-by: 3soatg53

secretGenerator:
- name: postgres-secret
  type: Opaque
  literals:
  - POSTGRES_PASSWORD=postgres

configMapGenerator:
- name: postgres-configmap
  literals:
  - POSTGRES_USER=postgres
  - POSTGRES_DB=fiap

generatorOptions:
  disableNameSuffixHash: false
