apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi  # Altere conforme necessário
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/host/postgres/data"  # Altere para o caminho desejado no host
