name: 3soat-g53 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build JAR with Maven
      run: mvn -B package --file pom.xml
    - name: Build Docker image
      run: docker build --file docker/Dockerfile -t local/applanchonetetok8s:latest .
    - name: Authenticate with AWS ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 339712845518.dkr.ecr.us-east-1.amazonaws.com/applanchonetetok8s
    - name: Tag Docker image
      run: docker tag local/applanchonetetok8s:latest 339712845518.dkr.ecr.us-east-1.amazonaws.com/applanchonetetok8s:latest
    - name: Push Docker image to AWS ECR
      run: docker push 339712845518.dkr.ecr.us-east-1.amazonaws.com/applanchonetetok8s:latest
